package com.demo.common.model;

import com.demo.common.model.base.BaseColumns;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Columns extends BaseColumns<Columns> {
	public static final Columns dao = new Columns().dao();
}
