package com.demo.common.model;

import com.demo.common.model.base.BaseNews;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class News extends BaseNews<News> {
	public static final News dao = new News().dao();
}
